name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
            
      - name: build
        run: |
          git rev-list --count HEAD
          python3 -m pip install --upgrade -q pip
          python3 -m pip install --upgrade -q build twine
          ls -la 
          git status 
          export COMMIT_CNT=`git rev-list --count HEAD` && python3 -c "import datetime; import os; v=datetime.datetime.utcnow().strftime('%y.%m.'); commit_cnt = os.environ['COMMIT_CNT']; print('__version__ = ' + f'\'{v}{commit_cnt}\'')" > ./src/screenshare/_version.py
          python3 -m build
          
      - name: publish
        run: |
          twine upload dist/* -u __token__ -p ${PYPI_TOKEN}
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}